version: '3.8'

services:
  app:
    image: nextcloud:fpm
    restart: always
    volumes:
      - ./container/html:/var/www/html
      - ./container/apps:/var/www/html/custom_apps
      - ./container/config:/var/www/html/config
      - ./container/data:/var/www/html/data
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.0.18:3000

  web:
    build: ./nginx
    restart: always
    ports:
      - 8080:80
      - 3000:443
    volumes:
      - ./container/html:/var/www/html
      - ../ssl/certs/:/etc/ssl/certs
      - ../ssl/private/:/etc/ssl/private
    depends_on:
      - app

  # web:
  #   image: nginx
  #   restart: always
  #   ports:
  #     - 8080:80
  #     - 3000:443
  #   volumes:
  #     - ./container/html:/var/www/html
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ../ssl/certs/:/etc/ssl/certs
  #     - ../ssl/private/:/etc/ssl/private