version: '3.8'

services:
  app:
    image: nextcloud:fpm
    restart: always
    volumes:
      - "${NEXTCLOUD_HTML}:/var/www/html"
      - "${NEXTCLOUD_APPS}:/var/www/html/custom_apps"
      - "${NEXTCLOUD_CONFIG}:/var/www/html/config"
      - "${NEXTCLOUD_DATA}:/var/www/html/data"
    environment:
      - "NEXTCLOUD_TRUSTED_DOMAINS=${NEXTCLOUD_DOMAIN}"

  web:
    build: ./nginx
    restart: always
    ports:
      - 8080:80
      - 3000:443
    volumes:
      - "${NEXTCLOUD_HTML}:/var/www/html"
      - ../ssl/certs/:/etc/ssl/certs
      - ../ssl/private/:/etc/ssl/private
    depends_on:
      - app
