version: '3.8'

services:
  server:
    build: .
    restart: always
    volumes:
      - "${TRILIUM_NODE_MODULES_DIR}:/root/trilium/node_modules"
      - "${TRILIUM_DATA_DIR}:/root/trilium-data"
    ports:
      - 8088:80
      - 3003:443