version: '3.8'

services:
  db:
    image: postgres:13.2-alpine
    restart: always
    environment:
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
      - TZ=America/Mexico_City
    volumes:
      - "${DB_DATA_PATH}:/var/lib/postgresql/data"
    ports:
      - 5432:5432